name: currency_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  retrofit: ^4.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  retrofit_generator: ^10.0.4

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/animation/
